-- 1. Create a table for student profiles
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  usn TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  password TEXT DEFAULT 'student1', -- Default password for current students
  face_descriptor JSONB, -- Store the 128D face descriptor from face-api.js
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create a table for attendance logs
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id),
  usn TEXT NOT NULL,
  status TEXT DEFAULT 'Present',
  marked_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Optional, for higher security)
-- ALTER TABLE students ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
